# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://192.168.0.60'
  # MQTT server authentication, uncomment if required:
  user: bogdan
  password: marus14kaMQT9

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  # Required: location of the adapter (e.g. CC2531).
  # To autodetect the port, set 'port: null'.
  port: /dev/ttyACM0
  # Optional: disable LED of the adapter if supported (default: false)
#  disable_led: false
  # Optional: adapter type, not needed unless you are experiencing problems (default: shown below, options: zstack, deconz, ezsp)
#  adapter: null
  # Optional: Baud rate speed for serial port, this can be anything firmware support but default is 115200 for Z-Stack and EZSP, 38400 for Deconz, however note that some EZSP firmware need 57600.
#  baudrate: 115200
  # Optional: RTS / CTS Hardware Flow Control for serial port (default: false)
#  rtscts: false

#advanced:
  # It is recommended to use a custom network key. This can be done by adding the following to your configuration.yaml. With this Zigbee2MQTT will generate a network key on next startup.
  # network_key: GENERATE
  # Optional: configure adapter concurrency (e.g. 2 for CC2531 or 16 for CC26X2R1) (default: null, uses recommended value)
  #adapter_concurrent: null
  # Optional: Transmit power setting in dBm (default: 5).
  # This will set the transmit power for devices that bring an inbuilt amplifier.
  # It can't go over the maximum of the respective hardware and might be limited
  # by firmware (for example to migrate heat, or by using an unsupported firmware).
  # For the CC2652R(B) this is 5 dBm, CC2652P/CC1352P-2 20 dBm.
  #transmit_power: 5

# To enable the frontend add the following (see the Frontend page for more settings):
#frontend: true
# Advanced configuration
#frontend:
  # Optional, default 8080
#  port: 8080
  # Optional, default 0.0.0.0. Opens a unix socket when given a path instead of an address (e.g. '/run/zigbee2mqtt/zigbee2mqtt.sock')
#  host: 0.0.0.0
  # Optional, enables authentication, disabled by default
#  auth_token: your-secret-token
  # Optional, url on which the frontend can be reached, currently only used for the Home Assistant device configuration page
#  url: 'https://zigbee2mqtt.myhouse.org'
  # Optional, certificate file path for exposing HTTPS. The sibling property 'ssl_key' must be set for HTTPS to be activated
#  ssl_cert: /config/etc/letsencrypt/live/mydomain.com/fullchain.pem
  # Optional, private key file path for exposing HTTPS. The sibling property 'ssl_cert' must be set for HTTPS to be activated
#  ssl_key: /config/etc/letsencrypt/live/mydomain.com/privkey.pem

devices:
  '0xa4c1381d4bac73c4':
    friendly_name: Toilet switch
  '0xa4c1385a4023c862':
    friendly_name: Shower switch
  '0x00158d0002e92036':
    friendly_name: Cabinet button
  '0x00158d000309b77f':
    friendly_name: Marry temp.sensor
  '0x01124b001bae7031':
    friendly_name: Vestibule switch
  '0x00158d0002e277eb':
    friendly_name: Entrance mov.sensor
  '0x00158d0002ec3034':
    friendly_name: Corridor mov.sensor
  '0x00158d00032c8fd1':
    friendly_name: Cabinet lamp center
  '0x00158d0002e8f460':
    friendly_name: Cabinet lamp die
  '0x00158d0002518c96':
    friendly_name: '0x00158d0002518c96'
  '0xa4c1384a9c741fe7':
    friendly_name: Cab. lamp Left new
  '0xa4c13817c959bada':
    friendly_name: 'Cab. lamp right new'
